'use client';

import * as React from 'react';
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Ban,
  Bell,
  BellRing,
  Boxes,
  Calendar,
  Camera,
  ChartColumn,
  ChartLine,
  ChartPie,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ClipboardList,
  Clock,
  Cpu,
  Database,
  Download,
  Ellipsis,
  EllipsisVertical,
  Eye,
  FileSpreadsheet,
  FileText,
  Filter,
  FlaskConical,
  Flag,
  GitBranch,
  Gauge,
  HelpCircle,
  House,
  IceCream2,
  Inbox,
  Info,
  Layers,
  Lightbulb,
  ListChecks,
  LoaderCircle,
  LogOut,
  Monitor,
  Package,
  PauseCircle,
  Pencil,
  Pin,
  PlayCircle,
  Plus,
  PlusCircle,
  Printer,
  Radar,
  RefreshCw,
  RotateCw,
  Save,
  ScanLine,
  Search,
  Send,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Star,
  StopCircle,
  Tag as TagIcon,
  Thermometer,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  User,
  Users,
  X,
  XCircle,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/**
 * Mapa de nombres de la librería de iconos de Figma (`Icon / line / <name>`)
 * a componentes de lucide-react. Fuente: docs/figma-kit.md §Iconos.
 */
export const iconMap = {
  // navegación / estructura
  'home-01': House,
  inbox: Inbox,
  monitor: Monitor,
  radar: Radar,
  categories: Layers,
  layer: Layers,
  package: Package,
  'tree-structure': GitBranch,
  'git-branch': GitBranch,
  database: Database,
  logout: LogOut,
  settings: Settings,
  'settings-02': Settings,
  sliders: SlidersHorizontal,
  // acciones
  plus: Plus,
  'plus-circle': PlusCircle,
  check: Check,
  'check-circle': CheckCircle2,
  'x-mark': X,
  'x-close': X,
  'x-mark-circle': XCircle,
  edit: Pencil,
  trash: Trash2,
  filter: Filter,
  download: Download,
  upload: Upload,
  save: Save,
  send: Send,
  search: Search,
  'search-lg': Search,
  printer: Printer,
  eye: Eye,
  camera: Camera,
  'scan-qr-code': ScanLine,
  'dots-horizontal': Ellipsis,
  'dots-vertical': EllipsisVertical,
  // flechas
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-path': RefreshCw,
  'rotate-right': RotateCw,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'trend-up': TrendingUp,
  'trend-down': TrendingDown,
  // avisos
  'bell-01': Bell,
  'bell-ringing': BellRing,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'info-circle': Info,
  'help-circle': HelpCircle,
  forbidden: Ban,
  'shield-check': ShieldCheck,
  verify: ShieldCheck,
  // tiempo
  clock: Clock,
  stopwatch: Timer,
  'calendar-01': Calendar,
  // datos / analítica
  chart: ChartColumn,
  'chart-alt2': ChartLine,
  'chart-pie': ChartPie,
  insight: Sparkles,
  'light-bulb': Lightbulb,
  activity: Activity,
  gauge: Gauge,
  zap: Zap,
  ranking: Star,
  star: Star,
  // archivos
  file: FileText,
  'file-xls': FileSpreadsheet,
  'file-csv': FileSpreadsheet,
  'file-pdf': FileText,
  'file-export': Download,
  'list-check': ListChecks,
  'task-list': ClipboardList,
  clipboard: ClipboardList,
  archive: Archive,
  tag: TagIcon,
  flag: Flag,
  pin: Pin,
  // personas
  user: User,
  'user-group': Users,
  // planta
  cpu: Cpu,
  flask: FlaskConical,
  'ice-cream': IceCream2,
  temperature: Thermometer,
  boxes: Boxes,
  'stop-circle': StopCircle,
  'play-circle': PlayCircle,
  'pause-circle': PauseCircle,
  // estado
  spinner: LoaderCircle,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;

const SIZE = { sm: 16, md: 20, lg: 24 } as const;

export interface IconProps extends Omit<React.SVGProps<SVGSVGElement>, 'ref'> {
  /** Nombre del icono en la librería de Figma. */
  name: IconName;
  /** 16 · 20 (por defecto) · 24 */
  size?: keyof typeof SIZE | number;
}

/** Wrapper de icono: 20 px por defecto, `currentColor`, trazo 1.75. */
export function Icon({ name, size = 'md', ...props }: IconProps) {
  const Cmp = iconMap[name];
  const px = typeof size === 'number' ? size : SIZE[size];
  return <Cmp width={px} height={px} strokeWidth={1.75} aria-hidden {...props} />;
}
